# rule identifiers to exclude from running
disabled_rules:
    - trailing_whitespace

#custom_rules:
line_length:
    warning: 150
    error: 200
    ignores_urls: true
    ignores_function_declarations: false
    ignores_comments: true
    ignores_interpolated_strings: true # default: false
